// Generated by CoffeeScript 1.9.3
var CLIEngine, ESLinter, chalk, pluralize;

chalk = require('chalk');

pluralize = require('pluralize');

CLIEngine = require('eslint').CLIEngine;

module.exports = ESLinter = (function() {
  function ESLinter() {}

  ESLinter.prototype.brunchPlugin = true;

  ESLinter.prototype.type = 'javascript';

  ESLinter.prototype.extension = 'js';

  ESLinter.prototype.lint = function(data, path, callback) {
    var errorCount, linter, result;
    if (path.indexOf("bower_components", 0) === 0) {
      callback();
      return;
    }
    linter = new CLIEngine({});
    result = linter.executeOnText(data, path).results[0];
    errorCount = result.errorCount;
    if (errorCount > 0) {
      console.warn("Linting of '" + result.filePath + "' failed with " + errorCount + " " + (pluralize('error', errorCount)) + ".");
      result.messages.forEach(function(warn) {
        return console.warn((chalk.yellow(warn.message)) + " (" + warn.line + ":" + warn.column + ")");
      });
    }
    return callback();
  };

  return ESLinter;

})();
